### ISSUE TITLE
-Link parameter not being passed to Docker

### ISSUE THREAD

**Issue by heiko-s** [dyson/dokku-docker-options#3]
Using latest dokku and docker. Trying to link running dokku RethinkDB instance to a second node.js app, which points to my root domain -> mydomain.com. Link parameter is correctly retrieved from DOCKER_OPTIONS file but isn't passed on to docker, as can be seen in the following dokku trace:

```
++ pluginhook docker-args mydomain.com
++ :
++ cat
+ STDIN=
+ APP=mydomain.com
+ DOCKER_OPTIONS_FILE=DOCKER_OPTIONS
+ DOCKER_OPTIONS_FILE_PATH=/home/dokku/mydomain.com/DOCKER_OPTIONS
+ output=
+ [[ -f /home/dokku/mydomain.com/DOCKER_OPTIONS ]]
+ read line
+ output=' -link rethinkdb_api:RETHINKDB'
+ read line
+ echo ' -link rethinkdb_api:RETHINKDB'
+ APP=mydomain.com
+ CONTAINER_NAME=rethinkdb_mydomain.com
+ VOLUME_DIR=/home/dokku/mydomain.com/rethinkdb
+ [[ -d /home/dokku/mydomain.com/rethinkdb ]]
+ DOCKER_ARGS=
++ docker run -d -p 5000 -e PORT=5000 app/mydomain.com /bin/bash -c '/start web'
+ id=85e8fe645f2182cf2c9bcd2967c35b77f261d7d3445578476df7fdc0056a5b98
+ echo 85e8fe645f2182cf2c9bcd2967c35b77f261d7d3445578476df7fdc0056a5b98
++ docker port 85e8fe645f2182cf2c9bcd2967c35b77f261d7d3445578476df7fdc0056a5b98 5000
```

Examinig DOCKER_OPTIONS file:
```
cat -E DOCKER_OPTIONS
```
...will print: 
```
-link rethinkdb_api:RETHINKDB$
```

Here's my list of dokku plugins:

/var/lib/dokku/plugins/00_dokku-standard/
/var/lib/dokku/plugins/backup/
/var/lib/dokku/plugins/config/
/var/lib/dokku/plugins/docker-options/
/var/lib/dokku/plugins/dokku-rebuild/
/var/lib/dokku/plugins/dokku-supervisord/
/var/lib/dokku/plugins/domains-plugin/
/var/lib/dokku/plugins/git/
/var/lib/dokku/plugins/nginx-vhosts/
/var/lib/dokku/plugins/rethinkdb/

A simple test that demonstrates that RethinkDB links should work:
```
sudo docker run -t -i -link rethinkdb_api:RETHINKDB ubuntu bash
env
```
...will correctly print RethinkDB env vars.

**Comment by dyson** [comment]
Better late than never I guess?

This is because we don't evaluate the options and so your env var is never evaluated. I wonder if this is a common enough thing people would want to do. The solution would be:

Adding
```bash
line=$(eval echo $line)
```
before adding the line to the output
```bash
output="$output $line"
```
to solve it but I am not sure how much of a bad idea this is.

**Comment by michaelshobbs** [comment]
@dyson I'm not clear on what env var needs to be evaluated here. It looks like the container name is "RETHINKDB" or am I completely missing something here?

**Comment by dyson** [comment]
Oh you are right, I thought the issue was trying to pass an env variable $RETHINKDB in the docker options which would be set on the dokku host.

My misinterpretation still raises an interesting use case though. With the evils of eval  and the fact people aren't screaming to be able to do this I suppose we just leave the current behaviour as.

More along, nothing to see here :wink:
