### ISSUE TITLE
docker run options break docker build

### ISSUE THREAD

**Issue by mc0e** [dyson/dokku-docker-options#5]
After building a container with a bind name server in it, I can open up ports with:

    dokku docker-options:add bind '--publish=53:53/udp --publish=53:53 --publish=953:953'

however, after doing this, a dokku rebuild (or git deploy) fails:

    Successfully built 66411ee1e17a
    -----> Deploying bind ...
    -----> Shutting down old containers
    time="2015-02-08T15:21:14+01:00" level="fatal" msg="Error response from daemon: Cannot start container 745b78958dcf9964a74b02763a4ede525d86958c5a3581404f29a0762a0b1691:  (exit status 1)" 

removing the options allows me to rebuild, and I can then re-add the options.

I haven't fully understood why this is happening, but I suspect it's necessary to have separate build options and run options.  Or maybe it's the shutdown options that need some special handling.

I'm not sure if it matters, but I'm running dokku-alt rather than the original dokku.

**Comment by dyson** [comment]
Hmm well I am not sure about dokku-alt but this issue came up it dokku because the docker-args plugin hook was added to the build process and some options being used during build cause failures.

You can have a look at this issue (https://github.com/progrium/dokku/issues/906) and the bunch of referenced issues in it. I will be updating the plugin sometime this week but no guarantee it will work in dokku-alt or that dokku-alt are going to handle the solution in the same way.

**Comment by dyson** [comment]
This is now being resolved in a new version supporting the build phases added to dokku.

https://github.com/dyson/dokku-docker-options/tree/dokku-merge
